### ISSUE TITLE
Bug in automatic merging process?

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/recipes-contrib#1076]
https://github.com/symfony/recipes-contrib/blob/master/README.rst says that a PR gets automatically merged if it's approved by:

> The user is a member of the organizations (publicly visible) for all modified packages.

Isn't this the case at https://github.com/symfony/recipes-contrib/pull/1075#pullrequestreview-565419301 ?

**Comment by fabpot** [comment]
This has been desactivated for a while now.
