### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by blink2004** [symfony/recipes-contrib#1131]
Hi,
Creating first Symfony app by tutorial https://symfony.com/doc/current/page_creation.html.
1. Done all from the page above.
2. Installed apache-pack by command:
`composer require symfony/apache-pack`
3. Check routes by command `$ php bin/console debug:router`:
    -------------------------- -------- -------- ------ -----------------------------------
     Name | Method | Scheme | Host | Path
    --- | --- | --- | --- |  ---
     ... | | | | 
    app_lucky_number | ANY | ANY | ANY | /lucky/number
4. Opened in browser ```http://<server_ip>/symfony/lucky/number``` and get 404 Apache error.
Opened in browser ```http://<server_ip>/symfony/public/``` and OK.
Opened in browser ```http://<server_ip>/symfony/public/index.php/lucky/number``` and OK.
5. Server:
  
    Q | A
    --- | ---
    OS |  5.8.0-50-generic #56~20.04.1-Ubuntu SMPx86_64
    Web Server | 2.4.41
    PHP | 7.4.3

**Comment by Nyholm** [comment]
It can be a handful of things. Is `.htaccess` enabled in subdirectries? Will it be the same if you set up a virtual host? 

I suggest checking on slack's #support or some other support channels: https://symfony.com/support
