### ISSUE TITLE
SKELETON_VERSION compatibility

### ISSUE THREAD

**Issue by ilvalerione** [symfony/recipes-contrib#1172]
Hi, I'm working on a new package: https://github.com/inspector-apm/inspector-symfony

Currently it is compatible with Symfony >= 5.2 but when I try to add the recipe to this repo it test the package for two skeletons: ^4.4, and ^5.0

Trevis report an error testing the package for Symfony ^4.4 (the package support Symfony >= 5.2) so I think the pull request can't be merged.

Is there a way to set the preferred skeleton version for the recipe? 

Thank you for your support.

**Comment by Nyholm** [comment]
If you look closely on the Github Action (and Travis) output, you will see a comment at the end saying "If your package does not support Symfony 4.4, feel free to ignore". 

Thank you for your PR. I'll close this issue now.
