### ISSUE TITLE
[bug] Flex Server: Unable to parse git ls-tree output

### ISSUE THREAD

**Issue by sroze** [symfony/recipes-contrib#125]
I'm not sure where to report this. While working on a contrib pull-request (#124) I am using the `SYMFONY_ENDPOINT` environment variable to use a given "pull-request environment". It was working impressively well yesterday, but this morning, Composer complained:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing sroze/openwhisk-bundle (0.2.0): Loading from cache
Writing lock file
Generating autoload files

Installation failed, reverting ./composer.json to its original content.


  [Composer\Downloader\TransportException]
  The "https://symfony.sh/r/github.com/symfony/recipes-contrib/124/p/sroze,openwhisk-bundle,i0.2.0,1509194154" file could not be downloaded (HTTP/1.1 500 Internal Server Error)
```

The `symfony.sh` URL returns the following:
```
< HTTP/1.1 500 Internal Server Error
< Content-Length: 34
< Content-Type: text/plain; charset=utf-8
< Date: Sun, 29 Oct 2017 09:33:01 GMT
< Vary: Origin
< X-Correlation-Id: khhctnfqwrbagxbu4budujoc
< X-Sensiocloud-Cache: MISS
< X-Sensiocloud-Cluster: egjbl6qhu5lse-master-7rqtwti
< X-Sensiocloud-Processor: 7zwai3z77ggmnxkao6dhwzsjxq
< X-Sensiocloud-Router: 3hjnjz4dfxtohh4gibk6eanr7y

unable to parse git ls-tree output
```

**Comment by sroze** [comment]
I was hoping amend+push on the branch would "refresh" the build and make this error disappear but it did not work.

One for you @tucksaun? Or @fabpot?

**Comment by Pierstoval** [comment]
In your composer cache directory (most of the time, `$HOME/.cache/Composer`) you can find a `repo` dir that contains a directory corresponding to your `SYMFONY_ENDPOINT`.

Have you tried clearing it?

**Comment by sroze** [comment]
@Pierstoval just to clarify: the "unable to parse git ls-tree output" error comes from the Flex Server (see the HTTP request).

**Comment by fabpot** [comment]
Whoops, my bad. Fixed now.
