### ISSUE TITLE
Flex server do not error when using an unknown endpoint

### ISSUE THREAD

**Issue by sroze** [symfony/recipes-contrib#129]
When using a wrong `SYMFONY_ENDPOINT` environment variable (I found this issue after my PR was merged), `composer req [...]` will not install the recipe but will succeed.

The reason for that is that the Flex server returns a valid JSON response for the `/p/[...]` API. Let's take the example of my merged PR #126:
1. The URL https://symfony.sh/r/github.com/symfony/recipes-contrib/126 displays "UNAVAILABLE" as it was merged, this makes sense. First of all, maybe it should return something else than 200. 404 maybe?
2. **The main issue:** The URL used by Composer (https://symfony.sh/r/github.com/symfony/recipes-contrib/126/p/sroze,openwhisk-bundle,i0.2.0,1509194154) returns a valid JSON response, but with no recipes:
```
{"locks":{"sroze/openwhisk-bundle":{"version":"0.2.0"}},"manifests":{},"vulnerabilities":{}}
```
(note that this will do the exact same with a PR number that do not exists at all either)

If this endpoint(s) would return an HTTP error, then the `composer req` would fail and this would make sense :)

**Comment by sroze** [comment]
@fabpot I guess you are one of the only ones with the 🔑

**Comment by fabpot** [comment]
1. fixed now, page returns a 404 now.

2. This one is more controversial as it means that the client must react to such a use case. I did it the current way to avoid that. If a recipe is not found in a repository (even when the repo does not exist), we fallback to the next repos (official ones). Anyway, I think it makes sense to change that. The server now returns a 404 in such a case. The error message is as follows on the client side:

[Composer\Downloader\TransportException]
  The "https://symfony.sh/r/github.com/symfony/recipes-contrib/126/aliases.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Not sure if this is enough, but I think that will do for now.

**Comment by sroze** [comment]
Seems good 👍 Thanks Fabien.

**Comment by fabpot** [comment]
reverted for now as it breaks a bunch of other things :(

**Comment by fabpot** [comment]
All was good afterall, false alarm.
