### ISSUE TITLE
Process Issue: Contributions are Often Stalled

### ISSUE THREAD

**Issue by amacrobert** [symfony/recipes-contrib#1461]
I am grateful for the time the core contributors spend reviewing PRs here, and understand there needs to be some quality control to prevent junk from making its way into this repo.

However, the review process as it stands can stall perfectly good contributions for lengthy and seemingly random time periods.

As of 2022-12-14, the oldest PR that passed all required checks but has not yet received an approval or change request is from 2021-05-10 -- about 19 months ago.

I made a PR for a new bundle in 2022-05-05 -- about 7 months ago -- that passes all required checks. Later, I [was informed](https://github.com/symfony/recipes-contrib/issues/1405) that 
> Your PR will be merged whenever a core team member reviews it, as outlined in the README of this repository: https://github.com/symfony/recipes-contrib#contributing That usually happens within a month or so.

It's understandable that there would be some delay, as the core contributors are volunteers and are not incentivized or compelled to review public PRs.

However, I believe there needs to be some change that allows good PRs to get into `main` in a timely or predictable manner, so that Symfony developers are not blocked from getting quality recipes for the packages they use.

I do not have a solution to propose. I am opening this issue to discuss possible process changes to address this issue.

**Comment by fabpot** [comment]
The only possibility I can see here is to auto-merge any contribution for which tests pass and without any requests for changes. Afterall, that's the goal of the contrib recipe repository: be as open as possible.

**Comment by fabpot** [comment]
And then, I've just reviewed 2 PRs randomly, and clearly, both of them should not be merged: https://github.com/symfony/recipes-contrib/pull/1433#pullrequestreview-1218678533 and https://github.com/symfony/recipes-contrib/pull/1430#pullrequestreview-1218676594

So, I think merging automatically is not a good idea after all. It means we need more volunteers to help.

**Comment by vvasiloi** [comment]
A lot of tests fail because the package doesn't support one of the Symfony versions the tests run against.
This issue alone creates a lot of stale PRs. 
Another one is that some packages support outdated versions of Symfony and/or PHP, which also make the tests fail.
I think we should make them a little bit more tolerant.

**Comment by amacrobert** [comment]
> So, I think merging automatically is not a good idea after all. It means we need more volunteers to help.

Some thoughts:

1. Could we auto-merge PRs after 90 days? They would have to pass (required) checks and **not** have a pending change request. This might actually motivate core members to review more often, since there's a time limit on when their review holds power.
2. In either case, if the solution required more volunteers, I think there should be clear instructions on how to become a volunteer.

**Comment by VincentLanglet** [comment]
> This might actually motivate core members to review more often

This won't add any motivation, just unnecessary pressure or merge PR which shouldn't be merged.
I would say volunteers are running out of time, not motivation.

**Comment by CJayHe** [comment]
My pr hasn't passed in months with no feedback, and it's seriously affecting my plans to release new features. 
#1444

**Comment by fabpot** [comment]
@CJayHe I've just reviewed your PR.

**Comment by fabpot** [comment]
I will close this issue now as it's not actionable.
I've spent a lot of time reviewing/merging/closing PRs and we're now in a good state.
Reviewing PRs can also be done by non-core-team members and we definitely need help here.
