### ISSUE TITLE
Testing contribution before making a PR

### ISSUE THREAD

**Issue by rande** [symfony/recipes-contrib#149]
Hello,

I might be blind, but I cannot find a way to test my contributions before sending a PR ...

Thanks

**Comment by Pierstoval** [comment]
Testing a recipe needs Flex to use the symfony.sh endpoint, so you must make a PR to be able to retrieve this endpoint from @symfony-bot and test it on your machine

**Comment by fabpot** [comment]
Indeed, you must submit a PR to test if that works.

**Comment by rande** [comment]
@fabpot @Pierstoval thanks
