### ISSUE TITLE
Why not allow aliases for contrib recipes?

### ISSUE THREAD

**Issue by maidmaid** [symfony/recipes-contrib#158]
It would be allowed with some restrictions, like
- only one allowed unique alias,
- required prefix like `_` for marking a difference with official recipes (example: `_elastica`).

**Comment by fabpot** [comment]
An alias is an opinion about which package gets the alias. You can only have one `admin` alias, so it must be chosen carefully. The contrib repository is about the possibility to add any package without any opinion about its usefulness or quality. That's why we don't accept aliases here.

**Comment by Pierstoval** [comment]
An alias needs to be opinionated. For example, if you want an oauth authentication in your app, will you use `knpuniversity/oauth2-client-bundle` ? `hwi/oauth-bundle` ? Or any other?

To avoid having fights about this, aliases are only available in the `recipes` repo, where the symfony core team can decide internally. The `recipes-contrib`  repo is for _all the community_, so it's already expected that no final decision could be made on a "final alias for the best option of {whatever-feature-need}".
