### ISSUE TITLE
[RFC] Let contributors be 100% responsible for their own recipe

### ISSUE THREAD

**Issue by maidmaid** [symfony/recipes-contrib#17]
This would relieve the time, effort and responsibility to core members. More, contributive recipes changes would be more quick and more active because they no longer depend on the expectation of a review/merge. To do this, @symfony-bot could be smart enough to merge PR when the following condition is valid:

```php
author username === root dir of all changed files
&& all checks in symfony.sh are green
&& 'Status: MERGE' === last comment
```

**Comment by stof** [comment]
the first condition you add would mean that any package owned by an organization would still require manual merging...

**Comment by maidmaid** [comment]
An improvement could be check also [list user organizations](https://developer.github.com/v3/orgs/#list-user-organizations); it's not technically impossible.

**Comment by fabpot** [comment]
Auto-merging is on my list. But first, I need to be sure that the validator checks are rock solid. We're getting there :) I need more PRs with human reviews. That helps me add more checks.

**Comment by maidmaid** [comment]
About this, will you make open-source the code that drives @symfony-bot?

**Comment by fabpot** [comment]
@maidmaid I have no plan to open-source the server part.

**Comment by fabpot** [comment]
PRs on this repository are now merged automatically. Rules are simple. PRs are merged when the following conditions are met (in that order):

 * The Symfony Bot approved the pull request and reported no validation errors;
 
 * Someone approved the pull request (it can be anyone but the original author of the pull request).

**Comment by fabpot** [comment]
Rules are still evolving, see #21 for more details
