### ISSUE TITLE
bot says to install flex 1

### ISSUE THREAD

**Issue by tacman** [symfony/recipes-contrib#1709]
![image](https://github.com/user-attachments/assets/bf2d8d00-2942-4d63-bcf2-955555fbf8bc)

from https://github.com/symfony/recipes-contrib/pull/1708

I think it'd be better if the bot simply said to install symfony/flex, without a specific version, so that version 2 can be installed.

Somewhat related, I'm not able to test my recipe, the instructions say to export the endpoint, but I'm always getting the recipe from :main.

**Comment by fabpot** [comment]
See https://github.com/symfony-tools/recipes-checker/pull/15
