### ISSUE TITLE
.htaccess file still set in "public" directory wether it been changed

### ISSUE THREAD

**Issue by julienborrel** [symfony/recipes-contrib#199]
Starting with a fresh install of Symfony with:
`$ composer create-project symfony/skeleton my_project`

I rename my `public` folder to `dist` as I need and add this to the `composer.json` file:
```javascript
// composer.json
{
    "...": "...",
    "extra": {
        "...": "...",
        "symfony-public-dir": "dist"
    }
}
```

then I run:
`$ composer require symfony/apache-pack`

Install is OK but the script create new `public` folder with the `.htaccess` file in it.

```
// directory structure
├─ dist/
│  └─ index.php
├─ public/
│  └─ .htaccess
```

What's wrong?

**Comment by Nyholm** [comment]
Thank you for this issue. 
Im afraid you posted it in the wrong repo. Could you move it to https://github.com/symfony/flex?

**Comment by OskarStark** [comment]
@Nyholm I guess you can close this one
