### ISSUE TITLE
Improve CI with prefer lowest

### ISSUE THREAD

**Issue by Jean85** [symfony/recipes-contrib#260]
I'm currently contributing a new recipe (#259) and I'm greatly appreciating the automatic review and CI process. 

I think that the second part, the CI on Travis, should be improved with a `--prefer-lowest` job, were we validate the fact that the lowest version defined by the contributed recipe is in fact correct.

**Comment by nicolas-grekas** [comment]
Closing as stalled.
For the record, https://github.com/symfony/recipes/tree/main/.github/workflows is the place where this could be implemented.
