### ISSUE TITLE
Recipes Server Guide for testing recipe locally is Linux-only

### ISSUE THREAD

**Issue by mhujer** [symfony/recipes-contrib#301]
This way if setting the ENV variable does not work on Windows:
```bash
export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/300
```

This must be used instead:
```cmd
SET SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/300
```

Similarly, instead of `unset SYMFONY_ENDPOINT` you have to use `SET SYMFONY_ENDPOINT=`.

So maybe the https://symfony.sh/r/github.com/symfony/recipes-contrib/300 should display both options?

**Comment by fabpot** [comment]
Fixed now. Thanks for sharing the right instructions for Windows.
