### ISSUE TITLE
dama_doctrine_test_bundle.yaml should be named without the _bundle suffix

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/recipes-contrib#311]
According to the naming convention we can see on all the repository.

cc @dmaicher

**Comment by dmaicher** [comment]
Was not aware of that :yum: Is it documented somewhere?

**Comment by Soullivaneuh** [comment]
> Is it documented somewhere?

Good question! :-)

I just saw that all configuration file name are without the _bundle.

But yeah, if the documentation does not exist, it should be added IMHO. :+1:

**Comment by Nyholm** [comment]
I do not think it matter to be honest. But you could submit a PR for consistency. I will close this issue though. 

Thank you @Soullivaneuh for reporting this.
