### ISSUE TITLE
RabbitMqBundle

### ISSUE THREAD

**Issue by skafandri** [symfony/recipes-contrib#37]
[php-apqmlib/RabbitMqBundle](https://packagist.org/packages/php-amqplib/rabbitmq-bundle) (800k downloads), recently renamed from [oldsound/RabbitMqBundle](https://packagist.org/packages/oldsound/rabbitmq-bundle) (1.2M downloads)

I am a maintainer of this bundle, if it looks interesting, I can come back with a PR.

**Comment by xabbuh** [comment]
Is there anything more to do than what was done in #20?

**Comment by skafandri** [comment]
oops! missed that one, sorry, closing this.
