### ISSUE TITLE
[symfony/apache-pack] Use DOCUMENT_ROOT to check if requested filename exist

### ISSUE THREAD

**Issue by natepage** [symfony/recipes-contrib#422]
I recently deployed one of my Symfony application on my production server, nothing fancy, but it was the first time I've set up a LAMP manually.

Before going further my configuration is as follows:
- CentOS Linux release 7.4.1708 (Core)
- Server version: Apache/2.4.29 (CentOS) Server built: Oct 23 2017 14:34:32
- PHP 7.1.14 (fpm-fcgi) (built: Feb  1 2018 15:33:20)
- Symfony 4.1.1

My application is simple, one controller, a few templates, and an SQLite database. I've used the `symfony/apache-pack` to set up my Apache configuration, and according to the documentation (https://symfony.com/doc/current/setup/web_server_configuration.html) I've moved the rewrite rules to my VirtualHost configuration.
I have some assets I include in my templates, for simplicity I've created them directly in my public folder, no symlinks.

My issue is that the rewrite rules are working fine, I can request my different routes I'm redirected to the front controller, but no styles on my pages because my assets are not loaded (404 Not found). The Rewrite rules from the `symfony/apache-pack` are supposed to take care of existing files and let the Apache server serve them but it didn't work for me.

After playing a bit (a few hours... haha) with the Rewrite rules I've realized the `%{REQUEST_FILENAME}` wasn't enough to check if the requested filename exists, so my solution was to prefix it using the `%{DOCUMENT_ROOT}`.

Here is my full VirtualHost:

```
<VirtualHost *:80>
    ServerName my-site.com
    ServerAlias my-site.com

    DocumentRoot /var/www/html/my-site.com/public
    DirectoryIndex index.php

    ErrorLog /var/www/html/my-site.com/error.log
    CustomLog /var/www/html/my-site.com/requests.log combined env=!dontlog

    <Directory /var/www/html/my-site.com/public>
        Require all granted
    </Directory>

    <FilesMatch \.php$>
        SetHandler proxy:fcgi://127.0.0.1:9000
    </FilesMatch>

    Options -MultiViews

    RewriteEngine On

    # Determine the RewriteBase automatically and set it as environment variable.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

    # Sets the HTTP_AUTHORIZATION header removed by Apache.
    RewriteCond %{HTTP:Authorization} .
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect to URI without front controller to prevent duplicate content.
    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

    # If the requested filename exists, simply serve it.
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule ^ - [L]

    # Rewrite all other queries to the front controller.
    RewriteRule ^ %{ENV:BASE}/index.php [L]
</VirtualHost>
```

Now it's pretty new for me to play with Apache VirtualHost and Rewrite rules, so my question is, is my solution legit or could it be because I've missed something in my VirtualHost configuration?

In the case this solution is a "good one" and could help others, I've taken the time to create a PR to update the `.htaccess` to add the RewriteCond, I'm using a `[OR]` condition to be backward compatible.

 Link to the PR: #421

**Comment by alquerci** [comment]
Hello @natepage 

Thanks to take time to report this issue. However it is more an issue on the documentation than on the code. See just below the explanation.

The file existence does not work on your side because you do not move `.htaccess` file content on ```

```
<Directory /var/www/html/my-site.com/public>
    # The content of `.htaccess` need to be here.
</Directory>
```

I hope this can help you to ease your understanding.

**Comment by Nyholm** [comment]
Thank you @alquerci for the explanation. 

If you think this still an issue, then we should open an issue on symfony/symfony-docs. 

#eu-fossa
