### ISSUE TITLE
Handle multiple recipes in one PR ?

### ISSUE THREAD

**Issue by mykiwi** [symfony/recipes-contrib#45]
It seems to not handle that use case, see #44  
Should I create one PR per recipe ?

**Comment by Pierstoval** [comment]
It's not because of the multiple recipes, it's because you have no release for your package

**Comment by mykiwi** [comment]
I get it, but [this page](https://symfony.sh/r/github.com/symfony/recipes-contrib/44) reference only the first one.

**Comment by Pierstoval** [comment]
Maybe you can try to release at least a 0.1 version for each package and rename the directories, at least to see if it's the bot who fails at first error or if it's another issue

**Comment by fabpot** [comment]
That's a bot bug :)

**Comment by fabpot** [comment]
fixed, you get all your errors now :)
