### ISSUE TITLE
FOSUserBundle recipe

### ISSUE THREAD

**Issue by maxhelias** [symfony/recipes-contrib#452]
I installed FOSUserBundle and saw that there was no recipe and looking here I saw a lot of PR for the same thing.

At first I do not understand why there were no recipes, so here is the thread

Issue in FriendsOfSymfony/FOSUserBundle#2704
Solution PR : FriendsOfSymfony/FOSUserBundle#2708

Recipe PR on this repo : 
- #270 -> Need to be review
- #343 -> Should be closed
- #345 -> Should be closed
- #363 -> Should be closed

Why do not we keep a valid one while waiting for the compatibility and close the others ?

**Comment by fabpot** [comment]
I've closed the 3 duplicated PRs.
