### ISSUE TITLE
Possible nelmio/alice recipie misconfiguration

### ISSUE THREAD

**Issue by gfilipiak** [symfony/recipes-contrib#455]
I am new to this stuff so tell me if I am wrong.

Regarding https://github.com/symfony/recipes-contrib/tree/master/nelmio/alice/3.2

manifest.json says:
```` json
"bundles": {
        "Nelmio\\Alice\\Bridge\\Symfony\\NelmioAliceBundle": ["dev", "test"]
    },
````
But directory structure is `config/packages/nelmio_alice.yaml`. This mean that it will be on in all environments including `prod` which is not listed in `bundles` so it fails to load the configuration for 'nelmio_alice'.

Tell me if I am right and I will try to provide PR for it to fix.

**Comment by theofidry** [comment]
Fixed by #487 or #486
