### ISSUE TITLE
Missing Resources/config in 3.4

### ISSUE THREAD

**Issue by wow-apps** [symfony/recipes-contrib#459]
Hi all.
I've got an issue in my bundle wow-apps/symfony-slack-bot

https://github.com/wow-apps/symfony-slack-bot/issues/3

**Let's start step-by-step:**

Configuration:

- Symfony 3.4.14
- PHP 7.1.16 (cli)
- Composer version 1.6.5 2018-05-04 11:44:59
- MacOS 10.13.6 (17G65)

1. Install:

```
alexeysamara: ~/projects/symfony-slack-bot/test/3.4  $ composer update
...
- Installing wow-apps/symfony-slack-bot (3.2.3): Downloading (100%)
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
```

2. Bundle were initialized in AppKernel.php

3. run console and got next result:

```
alexeysamara: ~/projects/symfony-slack-bot/test/3.4  $ ./bin/console

In FileLocator.php line 71:

  The file "services.yaml" does not exist (in: /Users/alexeysamara/projects/symfony-slack-bot/test/3.4/vendor/wow-apps/symfony-slack-bot/DependencyInjection/../Resources/config).
```

In package repository, you can find a services.yaml https://github.com/wow-apps/symfony-slack-bot/tree/master/Resources/config

**But, it was removed after installation by composer!**

![image](https://user-images.githubusercontent.com/2779949/44478430-5643b700-a646-11e8-8a9d-3a428af8aa4b.png)

I have a recipe https://github.com/symfony/recipes-contrib/tree/master/wow-apps/symfony-slack-bot/3.2 

Did somebody know, where is the problem?

Thank you.

**Comment by xabbuh** [comment]
The config file was committed in 2524102f5926fbb20944a6d784d6505daa05ba8f, but the latest release 3.2.3 does not contain this commit. I'm closing here as this needs to be fixed in the bundle.
