### ISSUE TITLE
[Bug] Recipe cached and not refreshed?

### ISSUE THREAD

**Issue by mykiwi** [symfony/recipes-contrib#50]
When I install my recipe (that is not yet merged), symfony flex use a recipe not up to date. Here it's what I do:

```bash
cd $(mktemp -d)
composer create-project symfony/skeleton .
composer config extra.symfony.allow-contrib true
export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/44
composer req "mykiwi/docker-symfony-php71-nginx-db-alpine:^0.4"
ls -l docker*
```

No `docker*` files are here, because the recipe downloaded is not sync with the recipe from the PR: 

`cat $HOME/.composer/cache/repo/https---symfony.sh-r-github.com-symfony-recipes-contrib-44/m-mykiwi-docker-symfony-php71-nginx-db-alpine-v0.4.1 | json_pp`

```
{
   "body" : {
      "version" : "0.4",
      "package" : "mykiwi/docker-symfony-php71-nginx-db-alpine",
      "manifest" : {
         "copy-from-package" : {
            "docker-compose.override.yml.dist" : "/",
            "docker" : "/",
            "docker-compose.yml" : "/"
         },
         "gitignore" : [
            "docker-compose.override.yml"
         ]
      }
   },
   "headers" : {
      "accept-ranges" : [
         "bytes"
      ],
      "last-modified" : [
         "Tue, 30 May 2017 07:03:27 GMT"
      ],
      "content-length" : [
         "229"
      ],
      "content-type" : [
         "application/json"
      ],
      "date" : [
         "Tue, 30 May 2017 09:02:18 GMT"
      ],
      "vary" : [
         "Origin"
      ],
      "connection" : [
         "close"
      ]
   }
}
```

But [my recipe](https://github.com/symfony/recipes-contrib/pull/44/files#diff-3a71bbf2e6c67ae00d0c5a7f2f767410) is actually:
```
{
    "copy-from-package": {
        "docker-compose.yml": "docker-compose.yml",
        "docker-compose.override.yml.dist": "docker-compose.override.yml.dist",
        "docker/": "docker/"
    },
    "gitignore": [
        "docker-compose.override.yml"
    ]
}
```

So maybe there is a cache problem somewhere in the infra?

**Comment by fabpot** [comment]
Fixed now. Can you confirm?

**Comment by mykiwi** [comment]
With `export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/51` yes 
With `export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/44` no, but it should since it's the same recipes.

**Comment by fabpot** [comment]
Now 44 and 51 are the same on the server (I didn't retriggered validation on PR 51). But you tell me that 51 is ok and not 44. I think that's the other way around.
