### ISSUE TITLE
How to test recipes locally

### ISSUE THREAD

**Issue by Aerendir** [symfony/recipes-contrib#509]
I'd like to create recipes for some of my open sourced bundles.

Before submitting a PR, I'd like to test the recipes locally.

Unfortunately I cannot find any information about how to do this, but [I know it is possible](https://github.com/symfony/recipes-contrib/pull/507#issuecomment-423849456).

Anyone that can explain me the flow to use to test locally the recipes? Thankyou!

ping @dunglas

**Comment by maxhelias** [comment]
It must have a private Flex server that allows this manipulation.
Otherwise, do your PR and when the `symfony-flex-server` is valid you can check your recipe like this:

```bash
# Create a new project
composer create-project symfony/skeleton:dev flex-dev
cd flex-dev
# And get your recipe
SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes/{PR} composer req {recipe}
```

**Comment by Aerendir** [comment]
Ok, @maxhelias , thank you for your fast reply.

I will try ASAP... In the mean time, thank you again!
