### ISSUE TITLE
GPL-2.0-or-later license not accepted?

### ISSUE THREAD

**Issue by emodric** [symfony/recipes-contrib#515]
I'm trying to add a recipe for `netgen/content-browser` which is licensed under "GPL 2.0 or later" license, but this is not accepted by Symfony Recipes Bot. Why is this license not accepted?

Does this mean that my open source package cannot be installed using Flex?

PR: https://github.com/symfony/recipes-contrib/pull/514
Check: https://symfony.sh/r/github.com/symfony/recipes-contrib/514

Thanks!

**Comment by emodric** [comment]
Can anyone help with this? @fabpot maybe? I'd like to round up my contributions to recipes so I can start using Flex soon :)

**Comment by fabpot** [comment]
We only accept MIT-like licenses, so no GPL.

**Comment by emodric** [comment]
@fabpot What could possibly be the reason for that?

https://spdx.org/licenses/ says that GPL 2.0 or later is both FSF free/libre and OSI approved, just like MIT is, so I don't see a reason why GPL 2.0+ should be denied.

Is there a chance this could be re-evaluated, since I think that choice of license (which in this instance is a true, open source, license) for a project should not be a deciding factor for it to be denied increase in developer experience when installing and using it. I'd understand if this policy were for official recipes repo (which it probably is), but I think it's a little bit discriminatory for "contrib" recipes.

**Comment by dunglas** [comment]
As a fervent advocate of GPL/AGPL for end users software, I'm in favor of allowing them.
However, we should not accept them for official recipes, and if we accept them here, we must display a warning pointing to the FSF website explaining the  implications of this license (basically, you cannot use them for a non-open source software in some cases).

**Comment by emodric** [comment]
Warning is fine as long as it doesn't make the user believe that they're doing something wrong, basically spreading FUD. Using GPL licensed packages is in most cases perfectly fine so singleing out packages or scaring users is definitely not desireable.

**Comment by dunglas** [comment]
It’s not a limitation, it’s the spirit of copyleft and it’s totally fair: to use free software, the deal is to contribute back.

**Comment by nicolas-grekas** [comment]
"recipes-contrib" is a very loosely opinionated repository, but it is still opinionated: copyleft licences are not accepted since day 1. The rationale is that Symfony is a project that targets professionals and enterprises. Copyleft licenses create legal risks because they need extra care. Not accepting them makes Symfony devs safe by default.
People that know how to deal with these licenses should also be perfectly capable of providing alternatives to this repository.
I agree with this policy personally as it's aligned with Symfony's mission statement.

:-1: to accept anything else than MIT and the likes.

**Comment by emodric** [comment]
I said it on Twitter, I don't think it's your job to police your users. I'd understand the policy if it were for the official `recipes` repo, or if it was a standalone tool. But, since Flex is a plugin for Composer, the decision does not make sense at all.

**Comment by nicolas-grekas** [comment]
A license is not an opinion, it's a legal document that judges can enforce. You can have opinions about licenses but they are not opinions by themselves. That's why I agree with Javier here.

**Comment by emodric** [comment]
A choice of license is an opinion, whether you like it or not. I'm willing to bet that most of developers choose their licenses based on their point of view and their opinion on how open source community should work.
