### ISSUE TITLE
Wrong test recipe URL on flex.symfony.com

### ISSUE THREAD

**Issue by Aerendir** [symfony/recipes-contrib#534]
I've just PRed a new bundle of mine and after all checks passed, going to the details of the check on the PR, I land on the page https://flex.symfony.com/r/github.com/symfony/recipes-contrib/531

This page shows me this screen:

<img width="1190" alt="schermata_2018-10-18_alle_17_32_18" src="https://user-images.githubusercontent.com/1968622/47166316-32c28300-d2fc-11e8-9378-f254fa2af7d1.png">

As you can see from the image, the two endpoints have different PR IDs: the correct one is `531`, but the endpoint for Mac/*nix is wrong as it is `521`.

**Comment by denisvmedia** [comment]
Yep, I faced the same issue.

**Comment by Aerendir** [comment]
Do you know who is in charge of fixing this?

cc @fabpot

**Comment by fabpot** [comment]
fixed now
