### ISSUE TITLE
Another approach to the manifest

### ISSUE THREAD

**Issue by 20uf** [symfony/recipes-contrib#55]
Hello,

I would like to know what is your interest in having a recipes repository for packages not maintained by Symfony?

Why not an approach of a manifest in the original repository?

Is it for the purpose of filtering ? 
Is not against the sense for the community?

The idea is good but there is a lot of constraint in this practice:
- Maintain this repository (versions ..)
- Being dependent on a response time / validation
- bundling of bundles

Regards,

**Comment by stof** [comment]
Well, PRs on this repo can be merged automatically by a bot once they fulfil the requirements. So this reduce the need for being dependent on response time or validation (the bot answers very fast).
Regarding versions, you will need to contribute a new version of the recipe only when the existing recipe is not compatible anymore with the new version of the bundle. This should not happen that often, unless you release BC-breaking versions of your bundle all the time (and then, your users will suffer anyway, so this is a bad strategy).

Having a central server is also necessary for some features: aliases (non-contrib only) but also some other features which are on @fabpot's TODO list. This has been discussed several times already (on Slack, on the recipes repo, on the flex repo, and maybe also on this repo).

On a side note, it also means that the server can perform transformations of the recipe content. The recipe being used by flex is actually a single JSON file, not something spread among multiple files (the goal is to have the flex plugin getting the bets format for it to work, and having maintainers writing the best format for them, which is not the same)

**Comment by torinaki** [comment]
@20uf faced the same issue. See discussion symfony/flex#206
