### ISSUE TITLE
[IvoryCKEditorBundle] Prepare for new major release (6.x)

### ISSUE THREAD

**Issue by egeloen** [symfony/recipes-contrib#57]
Hey!

I'm going to release the new major release (6.x) of IvoryCKEditorBundle due to a license mismatch... The new version removes CKEditor source from the bundle and introduce a command to easily download/install it by your own. Since Flex should automate most of the installation process, I open this issue in order to discuss what should/can be done here.

My interest is first to allow to install the 6.x version as well as automate the CKEditor installtion. There is two choices:
 1) Just inform user that the installation is not complete, it should now install CKEditor with the command
 2) Automatically append the command as Composer script (after clear cache but before assets install)

WDYT?

**Comment by fabpot** [comment]
Do you have a link to share where you discuss that? I'd like to better understand what the CKEditor installation means.

**Comment by Pierstoval** [comment]
As it's a bundle, I would you to handle CKEditor download with a Symfony command, and when IvoryCKEditor bundle is installed via Flex, add a message to the output saying that CKEditor has to be downloaded.

Also, I don't know how this external asset will be handled by the bundle, but maybe you should also suggest this via bundle configuration

**Comment by robfrawley** [comment]
CKEditor is licensed under the GPL, LGPL, MPL, and a commercial version with special licensing (yeah, it is distributed under four different licenses). Also, does the bundle's installation command allow for selecting the different versions of CKEditor (ie. "Basic," "Standard," "Full," etc)?

**Comment by Pierstoval** [comment]
It depends whether "canonical" links exist for these CKEditor editions or not 😕

**Comment by robfrawley** [comment]
Links to the different package versions do exist using the following pattern: 

```
http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.7.0/ckeditor_([0-9\.]{3})_(basic|standard|full).zip
```

**Comment by egeloen** [comment]
I will try to respond to all of your questions :)

> Do you have a link to share where you discuss that? I'd like to better understand what the CKEditor installation means.

Basically, the discussion started here: https://github.com/egeloen/IvoryCKEditorBundle/issues/295 & https://github.com/egeloen/IvoryCKEditorBundle/pull/298

Before the linked PR, CKEditor source was packaged with the bundle but now, you need to install it by you own:
 1) Manually by yourself and reconfigure the bundle to use it: http://symfony.com/doc/current/bundles/IvoryCKEditorBundle/usage/version.html
 2) Use the new built-in command: http://symfony.com/doc/current/bundles/IvoryCKEditorBundle/usage/ckeditor.html

> Does the bundle's installation command allow for selecting the different versions of CKEditor (ie. "Basic," "Standard," "Full," etc)?

Yes, you can choose where to install it, which distro to install (full, basic or standard, default full) as well as which specific version you want (default latest)...

**Comment by stof** [comment]
What you could do is providing a composer script handling the download of CKEditor (basically calling the command automatically, with checks to be sure it needs to be done again), and then update the recipe to register this script automatically.

**Comment by egeloen** [comment]
@stof Is it mandatory to create a script handler as I notice that you can directly put the command as a script in your composer.json file?

**Comment by fabpot** [comment]
Can we close here?

**Comment by Nyholm** [comment]
I’m closing this due inactivity.
