### ISSUE TITLE
[symfony-flex-server] auto validation status is frozen

### ISSUE THREAD

**Issue by nikossvnk** [symfony/recipes-contrib#616]
The status page of symfony-flex-server validation keeps saying `The pull request does not exist, is closed, or has already been merged.` at PR #613 

more specifically: I opened a PR and the validation result required changes. I amended my last commit and force-pushed my changes in my branch. The validation didn't run again and kept being at `Pending` state. So, I closed the PR, and opened a new one (thinking that now it will rerun). But, again, the status of symfony-flex-server was the one mentioned above. After that, I tried opening a PR from a different branch, but still, the result is that the PR is closed/merged/deleted. Relevant PRs #611 #612 #613

**Comment by GregoireHebert** [comment]
I am in quite the same situation, I thought at first I forgot to do something, but never had the problem in the past. @symfony-flex-server[bot] seems not to be able do find the #650 ...
I was in the same pattern as you, with a force push, so I closed the original PR and opened a new one.
No luck there...

**Comment by fabpot** [comment]
This happen when there is version that the server is not able to understand/parse. For #650, that's versions like `v0.5.0.x-dev`. I've fixed the server and rerun it for #650 (works now).

**Comment by GregoireHebert** [comment]
Thank you @fabpot !
