### ISSUE TITLE
What should we do with duplicated env vars?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes-contrib#629]
We were discussing on Symfony's Slack about something related to Flex and someone mentioned that some recipes create duplicate env vars. For example, in a Symfony app that already uses Doctrine, this recipe -> https://github.com/symfony/recipes-contrib/blob/master/backup-manager/symfony/2.1/manifest.json creates a duplicate `DATABASE_URL` env var.

Is this something expected? Should we detect this and avoid creating the duplicated env var? Thanks.

**Comment by Nyholm** [comment]
It is something that is expected. 
I usually ask people to "namespace" the environment variables to allow the users to decide which ones they want to reuse. 

I see that your example with the backup-manager (created by me) is not namespaced...

Im not sure about the path forward...

**Comment by javiereguiluz** [comment]
Closing as "fixed" because this is expected and there's a solution for it. For the specific issue of backup-manager ... that can be tackled in their own repo. Thanks.
