### ISSUE TITLE
Crash when $choices' values are arrays

### ISSUE THREAD

**Issue by Daisuke-sama** [symfony/recipes-contrib#636]
Hi! I have one of my ENUM implemented like this
```
class VehicleColorType extends AbstractEnumType
{
    public const OTHER = 0;
    public const WHITE = 1;
    protected static $choices = [
        self::OTHER  => [
            'name' => 'Other',
            'code' => '',
        ],
        self::WHITE  => [
            'name' => 'White',
            'code' => '#FFFFFF',
        ],
   ];
}
```
And when I do, for example, findOneBy() request, I get an error like on the picture
![image](https://user-images.githubusercontent.com/16666335/54812876-4011de00-4c9d-11e9-84d1-9f842c00ed3b.png)

What do you think?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
