### ISSUE TITLE
Need help getting my PR merged

### ISSUE THREAD

**Issue by mmucklo** [symfony/recipes-contrib#651]
My PR has been sitting for 9 months or so - could someone assist me in what I need to do to get it merged?

https://github.com/symfony/recipes-contrib/pull/420

Thanks,

--Matt

**Comment by Nyholm** [comment]
Merged!

Im not sure why it was waiting so long. I must have missed it and it was a long time ago I went over all the "old" PRs. 
I did so earlier today and now I saw this issue =)

Sorry for the long delay and thank you for the ping.

**Comment by mmucklo** [comment]
Thanks!!!
