### ISSUE TITLE
[friendsofsymfony/jsrouting-bundle] bad configuration when using Flex with Symfony 3.4

### ISSUE THREAD

**Issue by igorbga** [symfony/recipes-contrib#673]
We are using Symfony 3.4 (current LTS) and Flex.

The recipe has configured everything according to the new file structure but it seems to have assumed that the app is a Symfony 4.X app so in the routing file reference it points to the file specifically create for symfony 4, the one that ends with "-sf4.xml".

Just removing the "-s4" part made everything work.

**Comment by Nyholm** [comment]
Yeah, that is the solution. They did it like that because they could not come up with any non BC breaking way of doing it. They maybe should be more clear with their instructions though. 

Good thing you solved it and shared.
