### ISSUE TITLE
Missing clear guides - where to create manifest.json ?

### ISSUE THREAD

**Issue by vatri** [symfony/recipes-contrib#678]
Hi.

There are no clear (step by step) instructions on the internet on how to create a recipe.

By combining info from multiple links, I done following:

- created a new repo on my Github 
- created manifest.json + other needed files on the same repo
- enabled Symfony Flex Server/bot on the same repo
- created a PR and it passed validation and I merged it to `master` branch - on the same repo

I "feel" that I done something wrong. Shall I fork symfony/recipes-contrib repo and make branch, do the changes and create a PR from there?

And again, the main reason I opened this issue is to suggest creating more brief instructions. I can do it as well once I figure out how this works.

If we want to make Symfony more popular and more competitive, we will need to work a lot.

Kind regards,
Boris

**Comment by bocharsky-bw** [comment]
Have you seen the link from https://flex.symfony.com/ - see "Create a recipe for a public package" link:
<img width="430" alt="Screen Shot 2019-06-13 at 10 29 19" src="https://user-images.githubusercontent.com/3317635/59412469-2d073980-8dc6-11e9-9e9a-779aa2c032ee.png">

It points to this README: https://github.com/symfony/recipes/blob/master/README.rst

**Comment by vatri** [comment]
@bocharsky-bw  I saw that and many other links.

Nobody says that first step is to fork this repo. 

Therefore, I figure it out so we can close this issue. 

Should we add this info to the readme(s) ?

**Comment by bocharsky-bw** [comment]
Please, feel free to propose some improvements in your opinion with a PR

**Comment by vatri** [comment]
@bocharsky-bw I did it on the symfony/recipes repo:

https://github.com/symfony/recipes/pull/610

Now I assume we can close this issue.
