### ISSUE TITLE
[Recipes doc] Need for documentation

### ISSUE THREAD

**Issue by Pierstoval** [symfony/recipes-contrib#7]
I think a recipe might need a link for its documentation.

As we already know that a recipe is "accepted" if it's well documented and maintained, it could be necessary to require the presence of a documentation link somewhere.

Most bundle proposals include "default options" in their configuration, it gives the end user an example of config, but a bundle can have a more complex config, and having a direct link to documentation might be interesting to just ctrl+click / copy/paste to get more information about the possible config options.

The link could either be in the config file or in the recipe file, I don't know what's the best option, but for example, the `SecurityBundle` has documentation links in its [security.yaml](https://github.com/symfony/recipes/blob/master/symfony/security-bundle/3.3/etc/packages/security.yaml) file, so it could be just a good practice.

What do you think?

**Comment by stof** [comment]
Having the documentation link in the config file looks wrong to me: most bundles don't need a config file in the recipe as their default config is fine.

I'm not sure about having a doc link in the recipe. People using flex will never see the recipe file. They will just do `composer require acme/awesome-bundle` and the recipe file will be used internally by the flex plugin.

So the best place to jave the doc link is still in the Packagist metadata IMO

**Comment by Pierstoval** [comment]
So we could require the package to have a `supports.docs` entry in the `composer.json` file, even though it's not largely used atm?
This way, Flex can show the documentation link on each package installation

**Comment by stof** [comment]
Well, many packages just use the readme for the doc. But we should encourage them to provide the link to the doc if they have it elsewhere

**Comment by chalasr** [comment]
I think the [`post-install.txt`](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/post-install.txt) is good enough for giving some hints like a link to a particular documentation.

**Comment by stof** [comment]
And I don't think flex should output the link to the doc of all installed packages. It would be spammy. `composer show acme/awesome-bundle` will already display it.

**Comment by Pierstoval** [comment]
Well then I consider it's case closed, if composer & post-install already give the necessary tools for it
