### ISSUE TITLE
Is it possible to provide recipes without Symfony 3 support?

### ISSUE THREAD

**Issue by a-r-m-i-n** [symfony/recipes-contrib#709]
Because, after several [attempts](https://github.com/symfony/recipes-contrib/pull/706) I ended up with an error during CI, that getRootNode() in Configuration is not existing.

**Comment by bocharsky-bw** [comment]
That's OK if tests partially failed because of not supporting Sf 3

**Comment by a-r-m-i-n** [comment]
Okay, cool. Then I will re-do my pull request. I thought if one test fails, you will not merge it.
