### ISSUE TITLE
[vich/uploader-bundle] Missing templates files ?

### ISSUE THREAD

**Issue by thiphariel** [symfony/recipes-contrib#73]
Hi.

I really don't know if I post it in the right place, but the bundle provides some twig templates which are not created at the configuration.

Composer found the recipe at the installation and create the `config/vich_uploader.yaml` but nothing in `templates`

Is it a wanted behaviour ? Maybe I should post it in the vich repo ?

Thanks !

**Comment by Koc** [comment]
Twig templates only needed for forms and form theme automatically registered in di-extension

**Comment by Koc** [comment]
See https://github.com/dustin10/VichUploaderBundle/pull/700

**Comment by fabpot** [comment]
Can we close here then?

**Comment by thiphariel** [comment]
I gonna take a look, thanks !
