### ISSUE TITLE
why bundle must be compatible with all symfony version ?

### ISSUE THREAD

**Issue by mbo2olivier** [symfony/recipes-contrib#813]
Hi,
I have a question:
why the bundle must be compatible with symfony 3.4, 4.4 and 5.0 ? i have just published a new bundle version for symfony 5 and i want to publish the related recipe too, but the TravisCI config only require version ^2.0 of my bundle which is only compatible for Symfony 5 project, how to solve this problem ?

**Comment by moufmouf** [comment]
You don't need to have support for all Symfony versions.
Some packages only support Symfony 4 or Symfony 5 and that's ok. Your PR can still be merged even if a build fails for an unsupported version.

See https://github.com/symfony/recipes-contrib/pull/606#issuecomment-487474953

**Comment by mbo2olivier** [comment]
thank you for that precision, I did not know.
So i can now close this issue.
