### ISSUE TITLE
[unite-cms] Getting it merged without support for Symfony 3.4

### ISSUE THREAD

**Issue by franzwilding** [symfony/recipes-contrib#817]
I created a PR to add a recipe for unite cms (core and admin bundle) https://github.com/symfony/recipes-contrib/pull/815, however we don't support Symfony 3 anymor and because of that travis is failing. 

Can someone help me out, getting the PR merged?

Thank you!

**Comment by bobvandevijver** [comment]
See #709. Should be fine.

**Comment by Nyholm** [comment]
It is fine. I opened #923 to show this better. 

I left you a review a while back on #815, could you have a look at that and I'll be happy yo merge your PR.
