### ISSUE TITLE
Travis keeps testing my bundle against Symfony 3.x and 4.x

### ISSUE THREAD

**Issue by wajdijurry** [symfony/recipes-contrib#942]
I've created a new Symfony bundle, but Symfony keeps testing this bundle against old versions of Symfony (3.x and 4.x), while my bundle supports at least Symfony 5.x.

What should I do ? Should I pass some parameter in composer.json or what ??
![Screenshot from 2020-05-24 04-49-02](https://user-images.githubusercontent.com/25797257/82743878-0691a280-9d7a-11ea-9ae1-07029537de3b.png)

**Comment by nusphere** [comment]
I wonder myself, because I have the same issue. But 3.4 and 4.4 are still LTS -> https://symfony.com/releases

**Comment by Nyholm** [comment]
Symfony 3.4 and 4.4 is still supported. 

Currently, 3.4 is allowed to fail. If 4.4 is failing it shows a message that you can ignore that failure if your bundle does not support sf 4.4. 

Note that Symfony 4.4 will still be supported in 2023.
