### ISSUE TITLE
Is a small project ok ?

### ISSUE THREAD

**Issue by leogout** [symfony/recipes-contrib#95]
Hello, I've created a [SEO generator](https://github.com/leogout/SeoBundle) with decent test coverage and documentation (to me). I've used it in multiple production projects with success. The thing is, it doesn't have plenty of stars and contribs like the others.
I'd like to make a PR to add it here. Is that ok? Or should I come back later when the project gets more notoriety?

Cheers.

**Comment by fabpot** [comment]
It's fine. This repository accepts all contributions, without any criteria, except the ones from the validator. So, feel free to open a pull request :)
