### ISSUE TITLE
Allow recipes for packages with other type than "symfony-bundle"

### ISSUE THREAD

**Issue by luca-rath** [symfony/recipes-contrib#984]
What is the reason against supporting recipes for packages with a different type than "symfony-bundle", if they want to register a bundle?
As far as I can see, the related code in `symfony/flex` has been removed [here](https://github.com/symfony/flex/commit/a4bea5a5265445f573266a6c8697513f80c223f0#diff-46b78198ae7ea525f04268205dd782c3L760).

Here is the error, which is happening: https://flex.symfony.com/r/github.com/symfony/recipes-contrib/983

I also found this [comment](https://github.com/symfony/flex/pull/612#issuecomment-616273414), but it hasn't been answered.

Thanks in advance!

**Comment by luca-rath** [comment]
Just saw, that e.g. the [SyliusInvoicingPlugin](https://github.com/Sylius/InvoicingPlugin/blob/5240cd8d9369c2f4fa3f3010f09afa1e9993eb9a/composer.json#L3) sets `sylius-plugin` as it's type, but there is still a [Recipe](https://github.com/symfony/recipes-contrib/blob/a701a4bcac78125a63455010936a0223682dde49/sylius/invoicing-plugin/0.5/manifest.json#L3), which registers the bundle. Why does it fail in my case?

**Comment by fabpot** [comment]
Fixed now
